// Code generated by MockGen. DO NOT EDIT.
// Source: jst/mutator.go

// Package jst is a generated GoMock package.
package jst

import (
	spec "github.com/go-openapi/spec"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockMutator is a mock of Mutator interface
type MockMutator struct {
	ctrl     *gomock.Controller
	recorder *MockMutatorMockRecorder
}

// MockMutatorMockRecorder is the mock recorder for MockMutator
type MockMutatorMockRecorder struct {
	mock *MockMutator
}

// NewMockMutator creates a new mock instance
func NewMockMutator(ctrl *gomock.Controller) *MockMutator {
	mock := &MockMutator{ctrl: ctrl}
	mock.recorder = &MockMutatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMutator) EXPECT() *MockMutatorMockRecorder {
	return m.recorder
}

// OnSchema mocks base method
func (m *MockMutator) OnSchema(s *spec.Schema) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnSchema", s)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnSchema indicates an expected call of OnSchema
func (mr *MockMutatorMockRecorder) OnSchema(s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnSchema", reflect.TypeOf((*MockMutator)(nil).OnSchema), s)
}
